Attribute VB_Name = "L1_Schneider_Input"
Attribute VB_Base = "0{00020820-0000-0000-C000-000000000046}"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Attribute VB_TemplateDerived = False
Attribute VB_Customizable = True
Attribute VB_Control = "Submittal, 1, 0, MSForms, CommandButton"

Private Sub Submittal_Click()

Call Schneider_Submittal

End Sub
